name: Publish OpenAPI to GitHub Pages

on:  
  push:
    branches:
      - main

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: '16.x'
      - name: Build
        env:
          ntapi: ${{ secrets.NTAPI }}
        run: |
          npm ci
          npm run build
          npm run build-deref
          npx pagecrypt ./apidoc.html _build/ntapi.html ${{ env.ntapi }}
      - name: Deploy to GitHub Pages
        run : npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
